backend:
  name: github
  repo: MorshedulHoque/linkedgage-website-v1  # Replace with your GitHub username and repository name
  branch: main  # Default branch (e.g., main or master)

media_folder: "public/uploads"  # Folder for uploaded media
public_folder: "/uploads"        # Public URL for media

collections:
  - name: "blog"                 # Collection name
    label: "Blog"                # Label in the CMS UI
    folder: "src/posts"          # Folder for storing blog posts
    create: true                  # Allow creation of new posts
    slug: "{{slug}}"              # Slug format for posts
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Created Date", name: "date", widget: "datetime" }
      - { label: "Meta Description", name: "meta_description", widget: "text" }
      - { label: "Meta Tags", name: "meta_tags", widget: "list" }
      - { label: "Body", name: "body", widget: "markdown" }
